import { useEffect, useRef, useState } from 'react';
import { LayoutDashboard, CarFront, Truck, Files, ArrowUpRight, ArrowRight, Plus, ChevronDown, Search, Download, RefreshCw, ClipboardPaste, MapPin, Clock3, Check, CheckCircle2, CircleHelp, ChevronLeft, ChevronRight, X, PackageCheck, ArrowDownToLine, Layers, AlertTriangle, Menu, MoreHorizontal } from 'lucide-react';
import type { Workspace, Project, Unit, Stage, Load } from './types';
import { api, Badge, Empty, formatDate, stageLabels, timezone } from './shared';
import ImportDialog from './ImportDialog';
import UnitDrawer from './UnitDrawer';
import LoadDialog from './LoadDialog';
import ProjectDialog from './ProjectDialog';
import AssignDialog from './AssignDialog';
import BulkEditDialog from './BulkEditDialog';
import CarrierAssignDialog from './CarrierAssignDialog';
import CarrierWorkspace, { CarrierProgress } from './CarrierWorkspace';
type View='overview'|'units'|'loads'|'packing'|'carriers';
const navigation=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'units',label:'Unit register',icon:CarFront},{id:'loads',label:'Load builds',icon:Truck},{id:'packing',label:'Packing lists',icon:Files},{id:'carriers',label:'Carriers',icon:Truck}] as const;
const stages:Stage[]=['unscheduled','scheduled','in_transit','delivered'];
const pageTitles:Record<View,string>={overview:'Operations overview',units:'Unit register',loads:'Load builds',packing:'Packing lists',carriers:'Carrier operations'};
function overdue(u:Unit){return !!u.eta&&Date.parse(u.eta)<Date.now()&&u.status!=='delivered';}
function loadStage(l:Load,units:Unit[]):Stage{const us=units.filter(u=>u.load_id===l.id);return us.length&&us.every(u=>u.status==='delivered')?'delivered':us.some(u=>u.status==='in_transit'||u.status==='delivered')?'in_transit':'scheduled';}

export default function App(){
  const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[ws,setWs]=useState<Workspace|null>(null),[view,setView]=useState<View>('overview');
  const [error,setError]=useState(''),[loading,setLoading]=useState(true),[toast,setToast]=useState(''),[sidebar,setSidebar]=useState(false);
  const [modal,setModal]=useState<'import'|'project'|'newload'|'assign'|'bulk'|'carrier'|'newcarrier'|null>(null),[unitId,setUnitId]=useState<string|null>(null),[loadId,setLoadId]=useState<string|null>(null);
  const [search,setSearch]=useState(''),[stage,setStage]=useState('all'),[listId,setListId]=useState('all'),[t1,setT1]=useState('all'),[attention,setAttention]=useState(false),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(1),[demoBusy,setDemoBusy]=useState(false);
  const [pageSize,setPageSize]=useState('200'),[selectCount,setSelectCount]=useState('200'),[unassignedOnly,setUnassignedOnly]=useState(true),[carrierFilter,setCarrierFilter]=useState('all'),[carrierArea,setCarrierArea]=useState('');
  const active=useRef(projectId);active.current=projectId;
  const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  function notify(message:string){setToast(message);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setToast(''),5000);}
  useEffect(()=>{let alive=true;api<Project[]>('/api/projects').then(ps=>{if(!alive)return;setProjects(ps);const saved=localStorage.getItem('ryan-project');setProjectId(ps.some(p=>p.id===saved)?saved!:ps[0]?.id||'');}).catch(e=>{if(alive){setError(e.message);setLoading(false);}});return()=>{alive=false;if(noticeTimer.current)clearTimeout(noticeTimer.current);};},[]);
  useEffect(()=>{if(!projectId)return;let alive=true;localStorage.setItem('ryan-project',projectId);setLoading(true);setWs(null);setError('');setSelected([]);setCarrierFilter('all');setCarrierArea('');setStage('all');setListId('all');setSearch('');setT1('all');setAttention(false);setPage(1);setUnitId(null);setLoadId(null);api<Workspace>(`/api/projects/${projectId}/workspace`).then(w=>{if(alive)setWs(w);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[projectId]);
  useEffect(()=>{setPage(1);},[search,stage,listId,t1,attention,pageSize,carrierFilter]);
  useEffect(()=>{setSelected([]);},[search,stage,listId,t1,attention,carrierFilter]);
  async function refresh(message?:string){const id=projectId;const w=await api<Workspace>(`/api/projects/${id}/workspace`);if(active.current===id){setWs(w);setError('');if(message)notify(message);}}
  async function reload(){if(!projectId){window.location.reload();return;}setLoading(true);try{await refresh();}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  function go(v:View){setView(v);setSidebar(false);}
  function showUnits(s='all',list='all',late=false){setCarrierFilter('all');setSearch('');setT1('all');setStage(s);setListId(list);setAttention(late);setView('units');setPage(1);}
  function openCarrier(id:string){setCarrierArea(id);go('carriers');}
  function carrierRegister(name:string|null){showUnits();setCarrierFilter(name===null?'none':ws?.carriers.find(c=>c.name===name)?.id||'all');}
  async function demo(){
    setDemoBusy(true);setError('');try{
      const known=projects.find(p=>p.customer==='DEMO DATA');if(known){setProjectId(known.id);return;}
      const p=await api<Project>('/api/projects','POST',{name:'Demo · Maxus transport',customer:'DEMO DATA',target:400});
      const iso=(h:number)=>new Date(Date.now()+h*3600000).toISOString();
      const rows=Array.from({length:24},(_,i)=>({brand:'MAXUS',vin:`LSFAM11A1RA${String(i+1).padStart(6,'0')}`,model:i%3===0?'MIFA 9':'Deliver 9',reference:`SPOT-${String(i+1).padStart(3,'0')}`,origin:'Zeebrugge',destination:i<8?'Rotterdam':i<16?'Nijmegen':'Utrecht',pol_country:'BE',pol_address:'Port compound',pod_country:'NL',dealer:i<8?'Rotterdam dealer':i<16?'Nijmegen dealer':'Utrecht dealer',price:'95.00',t1:i%3?'yes':'no',notes:'Sample vehicle · for demonstration only'}));
      await api(`/api/projects/${p.id}/import`,'POST',{packingList:'DEMO · Arrival manifest',rows});
      let w=await api<Workspace>(`/api/projects/${p.id}/workspace`);
      for(let i=0;i<3;i++){
        const l=await api<Load>(`/api/projects/${p.id}/loads`,'POST',{reference:`MX-00${i+1}`,carrier:'Sample Transport',truck:`DEMO-0${i+1}`,driver:'Demo driver',capacity:8,origin:'Zeebrugge',destination:['Rotterdam','Nijmegen','Utrecht'][i],etd:iso([-48,-4,12][i]),eta:iso([-30,-1,30][i])});
        const vins=rows.slice(i*8,i===2?20:(i+1)*8).map(r=>r.vin);
        await api(`/api/projects/${p.id}/loads/${l.id}/assign`,'POST',{unitIds:w.units.filter(u=>vins.includes(u.vin)).map(u=>u.id)});
        if(i<2)await api(`/api/projects/${p.id}/loads/${l.id}/milestone`,'POST',{field:'atd',value:iso(i===0?-47:-3)});
        if(i===0)await api(`/api/projects/${p.id}/loads/${l.id}/milestone`,'POST',{field:'ata',value:iso(-29)});
      }
      setProjects(await api<Project[]>('/api/projects'));setProjectId(p.id);notify('Sample project created. Your real project is still empty.');
    }catch(e){setProjects(await api<Project[]>('/api/projects').catch(()=>projects));setError((e as Error).message);}finally{setDemoBusy(false);}
  }
  const project=ws?.project||projects.find(p=>p.id===projectId);
  const units=ws?.units||[],loads=ws?.loads||[],lists=ws?.packingLists||[];
  const counts=Object.fromEntries(stages.map(s=>[s,units.filter(u=>u.status===s).length])) as Record<Stage,number>;
  const late=units.filter(overdue),missingActual=units.filter(u=>u.status==='delivered'&&!u.ata);
  const filtered=units.filter(u=>(carrierFilter==='all'||(carrierFilter==='none'?!u.carrier:u.carrier.toLowerCase()===ws?.carriers.find(c=>c.id===carrierFilter)?.name.toLowerCase()))&&(stage==='all'||u.status===stage)&&(listId==='all'||u.packing_list_id===listId)&&(t1==='all'||(t1==='unknown'?!u.t1:u.t1===t1))&&(!attention||overdue(u))&&`${u.vin} ${u.brand} ${u.model} ${u.reference} ${u.origin} ${u.destination} ${u.dealer} ${u.load_ref||''} ${u.carrier} ${u.truck}`.toLowerCase().includes(search.toLowerCase()));
  const limit=pageSize==='all'?Math.max(1,filtered.length):Number(pageSize);
  const pages=Math.max(1,Math.ceil(filtered.length/limit)),currentPage=Math.min(page,pages),visible=filtered.slice((currentPage-1)*limit,currentPage*limit);
  const candidates=filtered.filter(u=>(!unassignedOnly||!u.carrier)&&!selected.includes(u.id)),batchSize=Math.min(candidates.length,Math.max(0,Math.floor(Number(selectCount)||0)));
  function selectBatch(){setSelected(s=>[...s,...candidates.slice(0,batchSize).map(u=>u.id)]);}
  const detail=units.find(u=>u.id===unitId),loadDetail=loads.find(l=>l.id===loadId);
  const expected=project?.target||400,percent=Math.round(counts.delivered/expected*100);
  const budget=units.reduce((sum,u)=>sum+Number(u.price||0),0);
  function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(v=>v!==id):[...s,id]);}
  function table(rows:Unit[],checkboxes=false){return <div className="table-scroll"><table className="units-table"><thead><tr>{checkboxes&&<th className="checkbox-cell"><input type="checkbox" aria-label="Select this page" checked={!!rows.length&&rows.every(u=>selected.includes(u.id))} onChange={e=>setSelected(s=>e.target.checked?[...new Set([...s,...rows.map(u=>u.id)])]:s.filter(id=>!rows.some(u=>u.id===id)))}/></th>}<th>Vehicle / VIN</th><th>Status</th><th>Route</th><th>Carrier</th><th>Load</th><th>ETD</th><th>ETA</th><th>T1</th><th/></tr></thead><tbody>{rows.map(u=><tr key={u.id} className={selected.includes(u.id)?'row-selected':''}>{checkboxes&&<td className="checkbox-cell"><input type="checkbox" checked={selected.includes(u.id)} onChange={()=>toggle(u.id)} aria-label={`Select ${u.vin}`}/></td>}<td><button className="vin-link" onClick={()=>setUnitId(u.id)}>{u.vin}</button><div className="cell-secondary">{[u.brand,u.model].filter(Boolean).join(' ')||'Vehicle details not provided'}{u.reference&&<span className="ref-label">{u.reference}</span>}</div></td><td><Badge stage={u.status}/></td><td><div className="cell-route"><span>{u.origin||'Not set'}</span><ArrowRight size={12}/><span>{u.destination||'Not set'}</span></div><span className="cell-secondary">{u.dealer||u.packing_list||'—'}</span></td><td>{u.carrier?<button className="load-link" onClick={()=>openCarrier(ws!.carriers.find(c=>c.name.toLowerCase()===u.carrier.toLowerCase())?.id||'')}>{u.carrier}</button>:<span className="muted">Not assigned</span>}</td><td>{u.load_ref?<button className="load-link" onClick={()=>setLoadId(u.load_id)}>{u.load_ref}</button>:<span className="muted">Unassigned</span>}</td><td className="date-cell">{formatDate(u.etd,true)}</td><td className={`date-cell ${overdue(u)?'text-red':''}`}>{formatDate(u.eta,true)}{overdue(u)&&<span className="cell-secondary text-red">Overdue</span>}</td><td><span className={`t1 ${u.t1==='yes'?'t1-yes':''}`}>{u.t1==='yes'?<><Check size={11}/>Yes</>:u.t1==='no'?'No':'—'}</span></td><td><button className="icon-button" aria-label={`Edit ${u.vin}`} onClick={()=>setUnitId(u.id)}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table></div>;}
  function loadCard(l:Load){const assigned=units.filter(u=>u.load_id===l.id),s=loadStage(l,units);return <button key={l.id} className="load-card" onClick={()=>setLoadId(l.id)}><div className="load-top"><span className="load-symbol"><Truck size={20}/></span><span className="load-reference">{l.reference}<small>{l.carrier||'Carrier not set'}</small></span><Badge stage={s}/></div><div className="load-route"><div><i/><span>{l.origin||'Origin not set'}</span></div><div><i/><span>{l.destination||'Destination not set'}</span></div></div><div className="load-bottom"><span>{assigned.length}<em> / {l.capacity} units</em></span><span>ETD {formatDate(l.etd,true)}</span></div><div className="capacity-track"><i style={{width:`${Math.min(100,assigned.length/l.capacity*100)}%`}}/></div></button>;}
  return <div className="app-shell">
    <aside className={`sidebar ${sidebar?'is-open':''}`}>
      <a className="brand" href="#" onClick={e=>{e.preventDefault();go('overview');}}><span className="brand-mark"><Layers size={24}/></span><span>RYAN<span className="brand-caption">TRANSPORT OPERATIONS</span></span></a>
      <div className="workspace-label">WORKSPACE <span>01</span></div>
      <div className="project-switch"><div className="project-monogram">{project?.customer==='DEMO DATA'?'D':project?.customer.slice(0,1)||'P'}</div><div><span>Active project</span><select aria-label="Active project" value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><ChevronDown size={14}/></div>
      <div className="nav-label">OPERATIONS</div><nav>{navigation.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>go(n.id)}><n.icon size={18}/><span>{n.label}</span>{n.id==='units'&&<b>{units.length}</b>}{n.id==='loads'&&loads.length>0&&<b>{loads.length}</b>}{n.id==='carriers'&&ws&&ws.carriers.length>0&&<b>{ws.carriers.length}</b>}</button>)}</nav>
      <button className="new-project" onClick={()=>setModal('project')}><Plus size={16}/>New project</button>
      <div className="sidebar-bottom"><div className="workspace-note"><span className="live-dot"/><span>Workspace storage</span><small>Changes save to this workspace</small></div><div className="profile"><span>RC</span><div><strong>Operations workspace</strong><small>Local development</small></div></div></div>
    </aside>
    {sidebar&&<button className="sidebar-backdrop" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>}
    <main>
      <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setSidebar(true)}><Menu size={20}/></button><span>Workspace</span><ChevronRight size={13}/><strong>{pageTitles[view]}</strong></div><div className="topbar-right"><span className="environment-tag"><i/>Development workspace</span><button className="icon-button" aria-label="Refresh workspace" disabled={loading} onClick={reload}><RefreshCw size={16} className={loading?'spin':''}/></button></div></header>
      <div className="page-content"><div className="page-heading"><div><div className="eyebrow">{project?.customer||'TRANSPORT'} / PROJECT OPERATIONS</div><h1>{pageTitles[view]}</h1><p>{view==='overview'?'Every vehicle. Every movement. One clear view.':view==='units'?'Track each VIN from the packing list to final delivery.':view==='loads'?'Plan capacity, build movements, and keep milestones up to date.':view==='carriers'?'Split your VINs between carriers and compare planning and delivery progress.':'Your incoming vehicle manifests, organised by project.'}</p></div><div className="heading-actions"><a className={`secondary ${!units.length?'disabled':''}`} href={`/api/projects/${projectId}/export`} aria-disabled={!units.length} onClick={e=>{if(!units.length)e.preventDefault();}}><Download size={15}/>Export CSV</a><button className="primary" disabled={!ws} onClick={()=>setModal(view==='loads'?'newload':view==='carriers'?'newcarrier':'import')}><Plus size={17}/>{view==='loads'?'New load':view==='carriers'?'New carrier':'Import units'}</button></div></div>
      {error&&<div className="error page-error" role="alert">{error}<button className="text-button" onClick={reload}>Retry</button></div>}
      {project?.customer==='DEMO DATA'&&<div className="demo-banner"><CircleHelp size={16}/><span>Sample project · All vehicles, routes, and prices shown here are demonstration data.</span><button onClick={()=>setProjectId(projects.find(p=>p.customer!=='DEMO DATA')?.id||projectId)}>Back to real project<ArrowRight size={14}/></button></div>}
      {loading&&!ws?<div className="loading-state"><RefreshCw size={24} className="spin"/><p>Loading your operations…</p></div>:ws&&<>
      {view==='overview'&&<>
        <section className="project-banner"><div><span className="project-pill"><span/>ACTIVE PROJECT</span><h2>{project?.name}</h2><p>{expected.toLocaleString()} expected vehicles <span>•</span> {lists.length} packing {lists.length===1?'list':'lists'} <span>•</span> {loads.length} load {loads.length===1?'build':'builds'}</p></div><div className="project-progress"><div><span>Delivery progress</span><strong>{percent}<small>%</small></strong></div><div className="progress-bar"><i style={{width:`${Math.min(100,percent)}%`}}/></div><p>{counts.delivered} of {expected} expected units delivered</p></div><div className="banner-art"><Truck size={120} strokeWidth={.65}/></div></section>
        <div className="metric-grid"><button className="metric" onClick={()=>showUnits()}><div className="metric-top"><span>Total imported</span><span className="metric-icon neutral"><CarFront size={19}/></span></div><div className="metric-value">{units.length}<small>/ {expected}</small></div><div className="metric-footer"><span className="metric-dot neutral"/>{Math.max(0,expected-units.length)} expected units not yet imported<ArrowUpRight size={13}/></div></button><button className="metric" onClick={()=>showUnits('scheduled')}><div className="metric-top"><span>Scheduled</span><span className="metric-icon blue"><Clock3 size={19}/></span></div><div className="metric-value">{counts.scheduled}<small>units</small></div><div className="metric-footer"><span className="metric-dot blue"/>{counts.unscheduled} units awaiting scheduling<ArrowUpRight size={13}/></div></button><button className="metric" onClick={()=>showUnits('in_transit')}><div className="metric-top"><span>In transit</span><span className="metric-icon amber"><Truck size={19}/></span></div><div className="metric-value">{counts.in_transit}<small>units</small></div><div className="metric-footer"><span className="metric-dot amber"/>{late.length} units past estimated arrival<ArrowUpRight size={13}/></div></button><button className="metric" onClick={()=>showUnits('delivered')}><div className="metric-top"><span>Delivered</span><span className="metric-icon green"><PackageCheck size={19}/></span></div><div className="metric-value">{counts.delivered}<small>units</small></div><div className="metric-footer"><span className="metric-dot green"/>{missingActual.length?`${missingActual.length} delivered without an ATA`:'Arrival milestones tracked'}<ArrowUpRight size={13}/></div></button></div>
        {!units.length?<section className="getting-started"><div className="getting-started-copy"><div className="eyebrow">FROM SPREADSHEET TO OPERATIONS</div><h2>Your next movement<br/>starts with a VIN.</h2><p>Bring your Maxus packing list into a workspace built for the whole journey. Start with one VIN, or paste all 400.</p><div className="getting-started-actions"><button className="primary" onClick={()=>setModal('import')}><ClipboardPaste size={17}/>Paste your first packing list</button><button className="text-button" disabled={demoBusy} onClick={demo}>{demoBusy?'Preparing sample…':'Explore a sample project'}<ArrowUpRight size={15}/></button></div></div><div className="getting-started-steps"><div><span>01</span><div><strong>Import your vehicles</strong><p>Copy cells or VINs directly from Google Sheets.</p></div><ClipboardPaste size={22}/></div><div><span>02</span><div><strong>Build your loads</strong><p>Assign vehicles, carriers, routes, and planned dates.</p></div><Truck size={22}/></div><div><span>03</span><div><strong>Track the journey</strong><p>Record departure and delivery for each vehicle.</p></div><CheckCircle2 size={22}/></div></div></section>:<>
          <div className="overview-columns"><section className="panel movement-panel"><div className="panel-heading"><div><h3>Movement pipeline</h3><p>Live status across your imported vehicles</p></div><Layers size={19}/></div><div className="pipeline-track">{stages.map(s=><div key={s} className={s} style={{width:`${counts[s]/units.length*100}%`}}/>)}</div><div className="pipeline-legend">{stages.map(s=><button key={s} onClick={()=>showUnits(s)}><i className={s}/><span>{stageLabels[s]}</span><strong>{counts[s]}</strong></button>)}</div><div className="pipeline-bottom"><span>Recorded unit prices <strong>{budget.toLocaleString('en-GB',{style:'currency',currency:'EUR'})}</strong></span><span>{units.filter(u=>u.price).length} of {units.length} units priced</span></div></section><section className="panel attention-panel"><div className="panel-heading"><div><h3>Needs attention</h3><p>Keep the next movement on track</p></div><AlertTriangle size={18}/></div><button onClick={()=>showUnits('all','all',true)}><span className="attention-count">{late.length}</span><div><strong>Past estimated arrival</strong><small>ETA passed · arrival not recorded</small></div><ArrowUpRight size={16}/></button><button onClick={()=>showUnits('unscheduled')}><span className="attention-count muted-count">{counts.unscheduled}</span><div><strong>Awaiting scheduling</strong><small>Ready for a load or planned ETD</small></div><ArrowUpRight size={16}/></button></section></div>
          <section className="section"><div className="section-heading"><div><h3>Load builds <span className="count">{loads.length}</span></h3><p>Your latest planned and active movements</p></div><button className="text-button" onClick={()=>go('loads')}>View all loads<ArrowRight size={15}/></button></div>{loads.length?<div className="load-grid">{loads.slice(0,3).map(loadCard)}</div>:<div className="compact-empty"><Truck size={22}/><p>No loads yet. Plan the first movement for your imported vehicles.</p><button className="secondary" onClick={()=>setModal('newload')}><Plus size={14}/>Create load</button></div>}</section>
        </>}
        {units.length>0&&<CarrierProgress ws={ws} onOpen={openCarrier} onUnassigned={()=>carrierRegister(null)}/>}
        <section className="panel register-preview"><div className="panel-heading"><div><h3>Vehicle register <span className="count">{units.length}</span></h3><p>{units.length?'Latest imported units in this project':'Your imported VINs will appear here'}</p></div><button className="text-button" onClick={()=>go('units')}>Open register<ArrowRight size={15}/></button></div>{units.length?table([...units].reverse().slice(0,6)):<div className="empty-register"><div className="empty-table-head"><span>VEHICLE / VIN</span><span>STATUS</span><span>ROUTE</span><span>LOAD</span><span>ETA</span></div><div><CarFront size={25}/><p>No vehicles imported yet</p><span>Paste a packing list to start tracking.</span></div></div>}</section>
      </>}
      {view==='units'&&<section className="panel full-register"><div className="register-tabs"><button className={stage==='all'?'active':''} onClick={()=>{setStage('all');setAttention(false);}}>All vehicles <b>{units.length}</b></button>{stages.map(s=><button key={s} className={stage===s?'active':''} onClick={()=>{setStage(s);setAttention(false);}}>{stageLabels[s]}<b>{counts[s]}</b></button>)}</div><div className="register-toolbar"><div className="search"><Search size={17}/><input placeholder="Search VIN, reference, dealer, route…" value={search} onChange={e=>setSearch(e.target.value)} aria-label="Search units"/>{search&&<button className="icon-button" onClick={()=>setSearch('')} aria-label="Clear search"><X size={14}/></button>}</div><select aria-label="Filter packing list" value={listId} onChange={e=>setListId(e.target.value)}><option value="all">All packing lists</option>{lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select aria-label="Filter carrier" value={carrierFilter} onChange={e=>setCarrierFilter(e.target.value)}><option value="all">All carriers</option><option value="none">No carrier assigned</option>{ws.carriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Filter T1" value={t1} onChange={e=>setT1(e.target.value)}><option value="all">All T1 statuses</option><option value="yes">T1 · Yes</option><option value="no">T1 · No</option><option value="unknown">T1 · Not specified</option></select><label className="page-size-label">Rows per page<select aria-label="Rows per page" value={pageSize} onChange={e=>setPageSize(e.target.value)}>{['50','100','200','400','all'].map(n=><option key={n} value={n}>{n==='all'?'All vehicles':n}</option>)}</select></label><button className={`secondary ${attention?'filter-active':''}`} onClick={()=>setAttention(x=>!x)}><AlertTriangle size={14}/>Overdue</button></div>
        <div className="batch-selection"><label htmlFor="batch-count">Select next</label><input id="batch-count" type="number" min="1" max="10000" value={selectCount} onChange={e=>setSelectCount(e.target.value)} aria-label="Number of VINs to select"/><span>VINs in packing-list order</span><label className="batch-unassigned"><input type="checkbox" checked={unassignedOnly} onChange={e=>setUnassignedOnly(e.target.checked)}/>Without a carrier only</label><button className="secondary small-button" disabled={!batchSize} onClick={selectBatch}>Select {batchSize} VINs</button><small>{candidates.length} matching VINs available</small></div>
        {selected.length>0&&<div className="selection-bar"><span><Check size={15}/>{selected.length} vehicles selected</span><button className="text-button" onClick={()=>setSelected([])}>Clear</button>{!filtered.every(u=>selected.includes(u.id))&&<button className="text-button" onClick={()=>setSelected(filtered.map(u=>u.id))}>Select all {filtered.length} matching vehicles</button>}<button className="primary small-button" onClick={()=>setModal('carrier')}><Truck size={15}/>Assign to carrier</button><button className="secondary small-button" onClick={()=>setModal('bulk')}>Bulk edit</button><button className="primary small-button" onClick={()=>setModal('assign')}><Truck size={15}/>Assign to load</button></div>}
        {filtered.length?table(visible,true):<Empty icon={<CarFront size={28}/>} heading={units.length?'No matching vehicles':'Your vehicle register is empty'} body={units.length?'Try another search or change your filters.':'Paste VINs or your usual sheet columns to create the first packing list.'} action={units.length?undefined:'Import units'} onAction={()=>setModal('import')}/>}
        <div className="table-footer"><span>{filtered.length?`${(currentPage-1)*limit+1}–${Math.min(currentPage*limit,filtered.length)} of ${filtered.length} vehicles`:'0 vehicles'}<em>· Packing-list order</em></span><div><button className="icon-button" aria-label="Previous page" disabled={currentPage<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>{currentPage} / {pages}</span><button className="icon-button" aria-label="Next page" disabled={currentPage>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div>
      </section>}
      {view==='carriers'&&<CarrierWorkspace key={`${projectId}:${carrierArea}`} ws={ws} initialCarrier={carrierArea} onDone={refresh} onUnit={setUnitId} onLoad={setLoadId} onRegister={carrierRegister} onAdd={()=>setModal('newcarrier')}/>}
      {view==='loads'&&<><div className="load-overview"><div><Truck size={22}/><b>{loads.length}</b><span>Total loads</span></div><div><CarFront size={22}/><b>{units.filter(u=>u.load_id).length}</b><span>Assigned vehicles</span></div><div><Clock3 size={22}/><b>{counts.unscheduled}</b><span>Awaiting scheduling</span></div></div>{loads.length?<div className="load-grid all-loads">{loads.map(loadCard)}</div>:<section className="panel"><Empty icon={<Truck size={32}/>} heading="Plan your first movement" body="Create a load, set the carrier and route, then assign units from your packing lists. Use the same flow for shunting or dealer deliveries." action="Create a load" onAction={()=>setModal('newload')}/></section>}<div className="workflow-note"><CircleHelp size={17}/><p>Load capacity is checked when you assign vehicles. Record actual departure (ATD) and arrival (ATA) for the load, or edit milestones for an individual VIN.</p></div></>}
      {view==='packing'&&<>{lists.length?<div className="packing-grid">{lists.map(l=>{const us=units.filter(u=>u.packing_list_id===l.id),delivered=us.filter(u=>u.status==='delivered').length;return <section key={l.id} className="panel packing-card"><div className="packing-top"><span className="packing-symbol"><Files size={23}/></span><button className="icon-button" aria-label={`View ${l.name}`} onClick={()=>showUnits('all',l.id)}><ArrowUpRight size={18}/></button></div><h3>{l.name}</h3><p>Created {formatDate(l.created_at,true)}</p><div className="packing-stats"><div><b>{us.length}</b><span>Units on list</span></div><div><b>{delivered}</b><span>Delivered</span></div><div><b>{us.filter(u=>u.carrier).length}</b><span>Carrier assigned</span></div><div><b>{us.filter(u=>u.load_id).length}</b><span>On loads</span></div></div><div className="packing-progress"><i style={{width:`${us.length?delivered/us.length*100:0}%`}}/></div><button className="text-button" onClick={()=>showUnits('all',l.id)}>View vehicles<ArrowRight size={15}/></button></section>;})}</div>:<section className="panel"><Empty icon={<Files size={32}/>} heading="Turn your sheet into a packing list" body="Paste a named batch of vehicles. Re-importing the same VIN updates that vehicle and keeps your project free of duplicates." action="Import packing list" onAction={()=>setModal('import')}/></section>}<div className="workflow-note"><ClipboardPaste size={17}/><p>No Google sign-in is needed for paste imports. Copy cells directly from your shared sheet. Each VIN belongs to one current packing list per project.</p></div></>}
      <footer className="page-footer"><span><Layers size={13}/>RYAN · TRANSPORT OPERATIONS · v{__APP_VERSION__}</span><span>Times in {timezone} <i/> Data saved in this workspace</span></footer>
      </>}
      </div>
    </main>
    {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}<button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={15}/></button></div>}
    {modal==='project'&&<ProjectDialog onClose={()=>setModal(null)} onCreated={p=>{setProjects(ps=>[...ps,p]);setProjectId(p.id);go('overview');notify('Project created');}}/>}
    {modal==='import'&&ws&&<ImportDialog projectId={projectId} units={units} onClose={()=>setModal(null)} onDone={refresh}/>}
    {modal==='newload'&&ws&&<LoadDialog projectId={projectId} units={units} onClose={()=>setModal(null)} onDone={refresh}/>}
    {modal==='assign'&&ws&&<AssignDialog projectId={projectId} units={units} loads={loads} unitIds={selected} onClose={()=>setModal(null)} onDone={async m=>{await refresh(m);setSelected([]);}}/>}
    {(modal==='carrier'||modal==='newcarrier')&&ws&&<CarrierAssignDialog projectId={projectId} units={modal==='carrier'?units.filter(u=>selected.includes(u.id)):[]} carriers={ws.carriers} onClose={()=>setModal(null)} onDone={async m=>{await refresh(m);setSelected([]);}}/>}
    {modal==='bulk'&&ws&&<BulkEditDialog projectId={projectId} units={units.filter(u=>selected.includes(u.id))} suggestions={units} onClose={()=>setModal(null)} onDone={async m=>{await refresh(m);setSelected([]);}}/>}
    {detail&&ws&&<UnitDrawer key={detail.id} unit={detail} projectId={projectId} events={ws.events} onClose={()=>setUnitId(null)} onDone={refresh}/>}
    {loadDetail&&ws&&<LoadDialog key={loadDetail.id} load={loadDetail} units={units} projectId={projectId} onClose={()=>setLoadId(null)} onDone={refresh}/>}
  </div>;
}
