import { useEffect, useState } from 'react';
import { ArrowRight, ClipboardPaste, Plus, Truck } from 'lucide-react';
import { Badge, Empty, formatDate } from './shared';
import type { Stage, Workspace } from './types';
import CarrierUpdateDialog from './CarrierUpdateDialog';

export default function LoadBuildWorkspace({ws,pasteRequest,onDone,onLoad,onUnit,onManual,onRegister}:{ws:Workspace;pasteRequest:number;onDone:(message:string)=>Promise<void>;onLoad:(id:string)=>void;onUnit:(id:string)=>void;onManual:()=>void;onRegister:(name:string|null)=>void}){
  const [carrierId,setCarrierId]=useState(()=>{try{const saved=localStorage.getItem(`ryan-load-carrier-${ws.project.id}`);return ws.carriers.find(c=>c.id===saved)?.id||ws.carriers[0]?.id||'';}catch{return ws.carriers[0]?.id||'';}});
  const [pasting,setPasting]=useState(false),[search,setSearch]=useState(''),[poolOnly,setPoolOnly]=useState(false),[history,setHistory]=useState(false);
  const c=ws.carriers.find(c=>c.id===carrierId),assigned=c?ws.units.filter(u=>u.carrier.toLowerCase()===c.name.toLowerCase()):[];
  const pool=assigned.filter(u=>!u.load_id),active=ws.loads.filter(l=>c&&l.carrier.toLowerCase()===c.name.toLowerCase()&&(history||assigned.some(u=>u.load_id===l.id)));
  const visible=assigned.filter(u=>(!poolOnly||!u.load_id)&&`${u.vin} ${u.load_ref||''} ${u.truck} ${u.origin} ${u.destination}`.toLowerCase().includes(search.toLowerCase()));
  useEffect(()=>{if(pasteRequest)setPasting(true);},[pasteRequest]);
  function choose(id:string){setCarrierId(id);setSearch('');setPoolOnly(false);try{localStorage.setItem(`ryan-load-carrier-${ws.project.id}`,id);}catch{/* Browser preference is optional. */}}
  return <>
    <section className="panel load-carrier-picker"><div className="panel-heading"><div><h3>Choose the carrier to update</h3><p>Paste their entire sheet: built loads, unassigned VINs, and all milestone columns.</p></div><button className="secondary" onClick={onManual}><Plus size={15}/>New load</button></div>
      {ws.carriers.length?<div className="carrier-choice-grid">{ws.carriers.map(carrier=>{const us=ws.units.filter(u=>u.carrier.toLowerCase()===carrier.name.toLowerCase());return <button key={carrier.id} className={`carrier-choice ${carrierId===carrier.id?'chosen':''}`} aria-pressed={carrierId===carrier.id} onClick={()=>choose(carrier.id)}><span><Truck size={18}/><strong>{carrier.name}</strong><ArrowRight size={15}/></span><small>{us.length} VINs · {new Set(us.map(u=>u.load_id).filter(Boolean)).size} loads · {us.filter(u=>!u.load_id).length} not built</small></button>;})}</div>:<Empty icon={<Truck size={28}/>} heading="Assign a carrier to start pasting load sheets" body="Allocate a batch in Unit register first, then choose its carrier here." action="Open unit register" onAction={()=>onRegister(null)}/>}
    </section>
    {c&&<>
      <section className="panel load-sheet-heading"><div><div className="eyebrow">CARRIER SHEET</div><h2>{c.name}</h2><p>{assigned.length} allocated VINs · last sheet check {c.last_update?formatDate(c.last_update,true):'not checked yet'}</p></div><button className="primary" disabled={!assigned.length} onClick={()=>setPasting(true)}><ClipboardPaste size={17}/>Paste full batch for {c.name}</button></section>
      <div className="load-overview"><div><Truck size={22}/><b>{active.filter(l=>assigned.some(u=>u.load_id===l.id)).length}</b><span>Load builds</span></div><div><Truck size={22}/><b>{assigned.length-pool.length}</b><span>VINs on loads</span></div><div><Truck size={22}/><b>{pool.length}</b><span>Not load built</span></div></div>
      <div className="section-heading"><div><h3>Built loads</h3><p>Open a load to see its VINs, dates, and movement details.</p></div><label className="remember-mapping"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>Include empty load history</label></div>
      {active.length?<div className="load-grid all-loads">{active.map(l=>{const us=assigned.filter(u=>u.load_id===l.id);const stage:Stage=us.length&&us.every(u=>u.status==='delivered')?'delivered':us.some(u=>['in_transit','delivered'].includes(u.status))?'in_transit':'scheduled';return <button className="load-card" key={l.id} onClick={()=>onLoad(l.id)}><div className="load-top"><span className="load-symbol"><Truck size={20}/></span><span className="load-reference">{l.reference}<small>{l.truck||'Truck not supplied'}</small></span><Badge stage={stage}/></div><div className="load-route"><div><i/><span>{l.origin||'POL not set'}</span></div><div><i/><span>{l.destination||'POD not set'}</span></div></div><div className="load-bottom"><span>{us.length}<em> VINs</em></span><span>ETD {formatDate(l.etd,true)}</span></div></button>;})}</div>:<div className="compact-empty"><Truck size={22}/><p>No loads built for this carrier yet. Paste the full sheet to detect separated loads.</p></div>}
      <section className="panel carrier-detail load-full-batch"><div className="panel-heading"><div><h3>Full carrier batch</h3><p>All VINs stay visible together, including the unassigned remainder.</p></div><button className="text-button" onClick={()=>onRegister(c.name)}>Open register for bulk edit<ArrowRight size={14}/></button></div><div className="carrier-register-tools"><div className="search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search VIN, truck or load…" aria-label="Search load batch"/></div><label className="remember-mapping"><input type="checkbox" checked={poolOnly} onChange={e=>setPoolOnly(e.target.checked)}/>Show not load built only ({pool.length})</label></div>
        <div className="table-scroll"><table className="carrier-unit-table"><thead><tr><th>VIN</th><th>Load build</th><th>Status</th><th>Brand / model</th><th>Reference / appointment</th><th>ETD</th><th>ATD</th><th>ETA</th><th>ATA</th><th>Truck</th><th>POL</th><th>POD</th><th>Comments</th></tr></thead><tbody>{visible.map(u=><tr className={!u.load_id?'pool-row':''} key={u.id}><td><button className="vin-link" onClick={()=>onUnit(u.id)}>{u.vin}</button></td><td>{u.load_id?<button className="load-link" onClick={()=>onLoad(u.load_id!)}>{u.load_ref}</button>:<span className="sheet-tag pool">Not load built</span>}</td><td><Badge stage={u.status}/></td><td>{u.brand} {u.model}</td><td>{u.reference||'—'}</td>{(['etd','atd','eta','ata'] as const).map(f=><td className="date-cell" key={f}>{formatDate(u[f],true)}</td>)}<td>{u.truck||'—'}</td><td className="sheet-cell">{[u.pol_country,u.origin,u.pol_zipcode,u.pol_address].filter(Boolean).join(' · ')||'—'}</td><td className="sheet-cell">{[u.pod_country,u.destination,u.pod_zipcode,u.pod_address].filter(Boolean).join(' · ')||'—'}</td><td className="sheet-cell">{u.notes||'—'}</td></tr>)}</tbody></table></div><div className="table-footer"><span>{visible.length} matching VINs · all rows shown</span></div>
      </section>
    </>}
    {pasting&&c&&<CarrierUpdateDialog projectId={ws.project.id} carrier={c} units={ws.units} onClose={()=>setPasting(false)} onDone={onDone}/>}
  </>;
}
