import { useState } from 'react';
import { Settings, Trash2 } from 'lucide-react';
import type { Project, Workspace } from './types';
import { api, Field, Modal } from './shared';
export default function ProjectSettings({ws,onClose,onSaved,onDeleted}:{ws:Workspace;onClose:()=>void;onSaved:(p:Project)=>Promise<void>;onDeleted:(id:string)=>void}){
  const p=ws.project;
  const [name,setName]=useState(p.name),[customer,setCustomer]=useState(p.customer),[target,setTarget]=useState(String(p.estimated_target)),[mode,setMode]=useState(p.volume_mode),[deleting,setDeleting]=useState(false),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const updated=await api<Project>(`/api/projects/${p.id}`,'PATCH',{name,customer,target:Number(target),volume_mode:mode});await onSaved(updated);onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function remove(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(`/api/projects/${p.id}`,'DELETE',{confirmName:confirmation});onDeleted(p.id);onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal title={deleting?'Delete project':'Project settings'} subtitle={p.name} onClose={()=>{if(!busy)onClose();}}>
    <div className="modal-body">{!deleting?<>
      <form onSubmit={save}><div className="form-grid"><Field label="Project name *"><input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Customer / brand"><input maxLength={100} value={customer} onChange={e=>setCustomer(e.target.value)}/></Field></div>
      <Field label="Project volume"><select value={mode} onChange={e=>setMode(e.target.value as Project['volume_mode'])}><option value="estimate">Use an editable estimate</option><option value="packing_list">Use the packing-list total automatically</option></select></Field>
      <Field label="Estimated units *"><input required type="number" min={1} max={100000} step={1} value={target} onChange={e=>setTarget(e.target.value)}/></Field>
      <div className="info-box"><div><strong>{ws.units.length} unique VINs imported · {ws.packingLists.length} packing lists</strong><p>{mode==='packing_list'?`The dashboard volume will be ${ws.units.length}, replacing the estimate in progress calculations. It follows the unique VIN total automatically when you import more packing lists.`:'The dashboard uses your estimate. You can raise or lower it at any time, or choose the packing-list total when the manifest is final.'}</p><p>The imported count comes from actual VIN records. Re-pasting existing VINs keeps that count stable; omitted VINs stay in the project.</p></div></div>
      <div className="modal-footer"><button className="secondary" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save project settings'}<Settings size={16}/></button></div></form>
      <div className="project-delete-area"><div><strong>Delete this project</strong><p>Remove this project and its vehicles, loads, packing lists, carriers, prices, sheet checks, alerts and activity.</p></div><button className="danger-button" disabled={busy} onClick={()=>{setDeleting(true);setError('');}}>Delete project<Trash2 size={15}/></button></div>
    </>:<form onSubmit={remove}><div className="error"><strong>This permanently deletes {p.name}.</strong><p>{ws.units.length} VINs, {ws.loads.length} loads, {ws.packingLists.length} packing lists and {ws.carriers.length} carriers will be removed, including prices, dates, alerts and activity. Other projects are kept.</p><p>Keep a copy of your data folder if you need a full backup. A CSV export contains the unit register only.</p></div>{ws.units.length>0&&<a className="secondary project-export" href={`/api/projects/${p.id}/export`}>Export unit register CSV</a>}<Field label="Type the project name to delete"><input autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder={p.name}/></Field><div className="modal-footer"><button className="secondary" type="button" disabled={busy} onClick={()=>{setDeleting(false);setConfirmation('');setError('');}}>Keep project</button><button className="danger-button" disabled={busy||confirmation!==p.name}>{busy?'Deleting…':'Permanently delete project'}<Trash2 size={16}/></button></div></form>}{error&&<div className="error" role="alert">{error}</div>}</div>
  </Modal>;
}
